version: "3"

services:

  # !!! for capturing http logs uncomment when needed
  # agent.apisix:
  #   image: logmink/agent:0.9
  #   container_name: apisix
  #   network_mode: "service:apisix"
  #   depends_on:
  #     - apisix
  #   environment:
  #     PORT: 32000
  #     LOGMINK_HUB_URL: http://logmink.hub
  #     mongoUrl: mongodb://logmink.hub:27017/logdb-prod
  #   entrypoint: ["node", "agent.js"]

  apisix.saqal:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.11.0-debian}
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "19180:9180/tcp"
      - "19080:9080/tcp"
      - "19091:9091/tcp"
      - "19443:9443/tcp"
      - "19092:9092/tcp"
    networks:
      - saqal_intranet
      - saqal_dmz

  etcd:
    image: bitnami/etcd:3.5.11
    restart: always
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "12379:2379/tcp"
    networks:
      - saqal_intranet
      - saqal_dmz

networks:
  saqal_intranet:
    external: true
  saqal_dmz:
    external: true
