version: '3.8'

services:
  ldap.saqal:
    image: osixia/openldap:1.5.0
    container_name: ldap.saqal
    environment:
      LDAP_ORGANISATION: "Saqal Inc."
      LDAP_DOMAIN: "saqal.org"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - saqal_intranet

  ui.ldap.saqal:
    image: osixia/phpldapadmin:0.9.0
    container_name: ui.ldap.saqal
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap.saqal"
    ports:
      - "8081:80"
      - "16443:443"
    networks:
      - saqal_intranet
    depends_on:
      - ldap.saqal

volumes:
  ldap_data:
  ldap_config:

networks:
  saqal_intranet:
    external: true

